### ISSUE TITLE
Keyboard shortcut for switching to last active tabs

### ISSUE THREAD

**Issue by gaohan137** [xcv58/Tab-Manager-v2#16]
Is it possible to add in the shortcut functionality to go back and forth between two recently visited tabs? For instance, if previous tab is A and current tab is B, then a keyboard shortcut would enable users to go B -> A and, when pressed a second time, go A -> B. There are some extensions available in Chrome App store, but the one I used had performance issue and froze a lot.

**Comment by xcv58** [comment]
Thanks for using this extension.
There is no direct API to get the last active tab in Chrom: https://developers.chrome.com/extensions/tabs

But the feature is doable, there are a few blockers:
- [] The popup implementation restricts the App to track all tabs information in Chrome, we have to move to background.html implementation to keep track all tabs, #17
- [] Once we have background page, we can keep tracking the tabs information in entire lifecycle #19
- [] Add shortcuts work on all pages #18

**Comment by xcv58** [comment]
Fixed in a50426a687f052d7dff79d0e22dfcbd4f5bca156
